#REDES NEURONALES
#2019781(01) - 2020-II

**Grupo 5**

* Edward Carrillo eccarrilloe@unal.edu.co
* Eliana Garzón egarzonv@unal.edu.co
* Diego Velásquez arvelasqueza@unal.edu.co
* Sneyder Gantiva esgantivar@unal.edu.co



In [ ]:
import numpy as np

## Ejercicio 1
Considere el siguiente problema para ser resuelto con una red neuronal como se detalla a continuación.
El conjunto de entrenamiento es:

**input**

\begin{bmatrix}
1 & 0 & 0 & 0\\
1 & 1 & 0 & 0\\
0 & 0 & 0 & 1\\
0 & 0 & 1 & 1\\
\end{bmatrix}

**output**

\begin{bmatrix}
1 & 0 \\
1 & 0 \\
0 & 1 \\
0 & 1 \\
\end{bmatrix}

Considere una red neuronal de dos capas, una capa de entrada y una capa de salida. Las neuronas de la capa de salida son neuronas de McCulloch-Pitts con umbrales (biases) iguales a cero. Considere la siguiente regla para almacenar cada uno de los ejemplos (parejas entrada-salida) basada en el producto exterior (outer product) de dos vectores. 

El producto exterior de dos vectores se calcula como el **producto matricial de dos vectores**, escribiendo el primer vector como un vector columna (es decir, una matriz de tamaño nx1) y el segundo vector como un vector fila (y tratarlo como una matriz de tamaño 1xm). El resultado es entonces una matriz de tamaño nxm.


Entrada

In [ ]:
input = np.array([[1, 0, 0, 0], [1, 1, 0, 0], [0, 0, 0,1], [0, 0, 1, 1]])
input

array([[1, 0, 0, 0],
       [1, 1, 0, 0],
       [0, 0, 0, 1],
       [0, 0, 1, 1]])

Salida

In [ ]:
output = np.array([[1, 0], [1, 0], [0, 1], [0, 1]])
output

array([[1, 0],
       [1, 0],
       [0, 1],
       [0, 1]])

In [ ]:

def threshold(value):
  '''
  Función de umbral
  '''
  return 1 if value > 0 else 0

###(a) 
Considere que para almacenar el primer ejemplo, la matriz de pesos se calcula como el producto exterior entre la correspondiente entrada y salida de este ejemplo. Verifique que esto es cierto, es decir que cuando se ingrese el vector de entrada correspondiente, la salida es la deseada.


In [ ]:
weigths = np.zeros((4, 4, 2))

In [ ]:
for i in range(weigths.shape[0]):
  weigths[i] = np.outer(input[i], output[i])

In [ ]:
weigths

array([[[1., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[1., 0.],
        [1., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 1.]],

       [[0., 0.],
        [0., 0.],
        [0., 1.],
        [0., 1.]]])

In [ ]:
for i in range(weigths.shape[0]):
  result = input[i] @ weigths[i, :]
  for j in range(result.shape[0]):
    result[j] = threshold(result[j])
  print(result)

[1. 0.]
[1. 0.]
[0. 1.]
[0. 1.]


In [ ]:
output

array([[1, 0],
       [1, 0],
       [0, 1],
       [0, 1]])

### (b)	
Explique por qué este cálculo de la matriz de pesos corresponde a la aplicación de la regla de aprendizaje de Hebb.

> El cálculo de la matriz de pesos corresponde a la aplicación de la regla de Hebb porque el proceso de aprendizaje de Hebb afirma que si las neuronas de entrada y salida se activan sincronicamente, la conexión entre estas neuronas se refuera. Esto es similar a la regla delta ya que el valor de los pesos depende de las entradas y las salidas, y el calculo de los mismo se refuerza si hay una activación(valor 1) entre una entrada y la salida. 

###(c) 
¿Verifique si esto mismo se cumple si se considera almacenar de manera separada cada uno de los otros ejemplos?


> Resuelto en el punto a

###(d) 

Si ahora la matriz de pesos se calcula como la suma de las matrices de los pesos para cada uno de los ejemplos calculadas en los literales a) y c), verifique si la red neuronal es capaz de “recordar” todos los ejemplos de entrenamiento.

In [ ]:
weigths_sum = np.zeros((input.shape[0], output.shape[1]))

In [ ]:
for i in range(weigths_sum.shape[0]):
  weigths_sum += np.outer(input[i], output[i])

In [ ]:
weigths_sum

array([[2., 0.],
       [1., 0.],
       [0., 1.],
       [0., 2.]])

In [ ]:
for i in range(input.shape[0]):
  r = input[i] @ weigths_sum
  for j in range(r.shape[0]):
    r[j] = threshold(r[j])
  print(r)

[1. 0.]
[1. 0.]
[0. 1.]
[0. 1.]


In [ ]:
output

array([[1, 0],
       [1, 0],
       [0, 1],
       [0, 1]])

> Las salidas esperadas y las salidas calculadas son iguales

## Ejercicio 2.
Ahora considere una red neuronal similar a la del ejercicio anterior, pero ahora las neuronas de la capa de salida tienen como función de activación la identidad. También, considere el siguiente conjunto de ejemplos de entrenamiento, donde cada xi corresponde a la entrada de un ejemplo y $y_i$ a la salida correspondiente:

In [ ]:
X = np.array([[1,0,0,0], [0,1,0,0], [0,0,1,0]])
X

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0]])

In [ ]:
Y = np.array([[5,1,0], [-2,1,6], [-2,4,3]])
Y

array([[ 5,  1,  0],
       [-2,  1,  6],
       [-2,  4,  3]])

### (a)
Calcule la matriz de los pesos usando la misma regla del ejercicio anterior.

In [ ]:
weigths_2 = np.zeros((4, 3))

In [ ]:
for i in range(Y.shape[0]):
  weigths_2 += np.outer(X[i], Y[i])

In [ ]:
weigths_2

array([[ 5.,  1.,  0.],
       [-2.,  1.,  6.],
       [-2.,  4.,  3.],
       [ 0.,  0.,  0.]])

### (b)
Calcule las salidas para cada uno de los ejemplos de entrada: Analice los resultados.

In [ ]:
for i in range(X.shape[0]):
  print(X[i] @ weigths_2)

[5. 1. 0.]
[-2.  1.  6.]
[-2.  4.  3.]


> Aca podemos ver como para el ultimo parametro de entrenamiento no tiene influencia en la matrices de pesos porque entran uns parametros pero terminan en una salida 0,0,0,0 es decir esta cuarta componente no aporta nada al entrenamiento de la red.

### (c)
Calcule la respuesta y de la red neuronal cuando la entrada es 
$$x=[0.8, -0.15, 0.15,-0.20]^{T}$$

In [ ]:
x = np.array([0.8, -0.15, 0.15, -0.2])

In [ ]:
x @ weigths_2

array([ 4.  ,  1.25, -0.45])

### (d) 

También, compare este vector $x$ con el vector $x_1$.

Compare esta salida y con cada uno de los vectores $y_i$. ¿Qué observa?

> La salida $y$ es una combinación lineal de los vectores de salida del conjunto de entrenamiento, esto se debe a que el conjunto de entrada $X$ es la identidad, lo que implica que la memoria del sistema esta asociada a los vectores de salida.

$$y = Y_1 * 0.8 - Y_2 * 0.15 + Y_3 * 0.15 $$

## Ejercicio 3.
Ahora considere una red neuronal como la del ejercicio 2, en la cual el número de neuronas de entrada es igual al número de neuronas de salida. También, considere el siguiente conjunto de entrenamiento:

$$x_1 = \frac{1}{4}  [-2, -3, 3^{1/2}]^T$$

$$x_2 = \frac{1}{4} [2,-2, -(8^{1/2}) ]^T$$

$$x_3 = \frac{1}{4} [3,-1, 6^{1/2}]^T$$

In [ ]:
x_1 = (1/4) * np.array([-2, -3, np.sqrt(3)])
x_2 = (1/4) * np.array([2, -2, -np.sqrt(8)])
x_3 = (1/4) * np.array([3, -1, np.sqrt(6)])
x_1, x_2, x_3

(array([-0.5      , -0.75     ,  0.4330127]),
 array([ 0.5       , -0.5       , -0.70710678]),
 array([ 0.75      , -0.25      ,  0.61237244]))

### (a)
Realice el mismo cálculo de la matriz de pesos de los ejercicios anteriores.

In [ ]:
weigths_3 = np.outer(x_1, Y[0]) + np.outer(x_2, Y[1]) + np.outer(x_3, Y[2])

In [ ]:
weigths_3

array([[-5.        ,  3.        ,  5.25      ],
       [-2.25      , -2.25      , -3.75      ],
       [ 2.3545322 ,  2.17539566, -2.40552338]])

### (b)
Calcule las salidas cuando se introduce cada uno de los vectores de entrenamiento

In [ ]:
x_1 @ weigths_3

array([ 5.20704235,  1.12947395, -0.85412218])

In [ ]:
x_2 @ weigths_3

array([-3.03990569,  1.08676297,  6.20096189])

In [ ]:
x_3 @ weigths_3

array([-1.74564938,  4.14465234,  3.40192379])

###(c) 

Calcule los ángulos entre estos vectores de entrenamiento. ¿Qué tan cerca están de la ortogonalidad entre ellos?

Tomado de [Angles between two n-dimensional vectors in Python](https://stackoverflow.com/questions/2827393/angles-between-two-n-dimensional-vectors-in-python)

In [ ]:
def unit_vector(vector):
    """ Returns the unit vector of the vector.  """
    return vector / np.linalg.norm(vector)

def angle_between(v1, v2):
    """ Returns the angle in degrees between vectors 'v1' and 'v2'::
    """
    v1_unit = unit_vector(v1)
    v2_unit = unit_vector(v2)
    return np.degrees(np.arccos(np.inner(v1_unit, v2_unit)))

In [ ]:
angle_between(x_1, x_2)

100.43886125978185

In [ ]:
angle_between(x_1, x_3)

85.54563512995553

In [ ]:
angle_between(x_2, x_3)

86.15903428374187

> Ningun vector es ortogonal entre si, los vectores $x_2$ y $x_3$ son los que estan mas cerca de ser ortogonales

### (d)
Calcule la respuesta de la memoria cuando el estímulo aplicado a la red neuronal es:
$$x=[0, -3, 3^{1/2}]^T$$

In [ ]:
x_d = np.array([0, -3, np.sqrt(3)])
x_d

array([ 0.        , -3.        ,  1.73205081])

In [ ]:
x_d @ weigths_3

array([10.8281694 , 10.51789582,  7.08351129])